[Service]
UnsetEnvironment=__EGL_VENDOR_LIBRARY_FILENAMES __GLX_VENDOR_LIBRARY_NAME NVIDIA_VISIBLE_DEVICES VK_ICD_FILENAMES CUDA_VISIBLE_DEVICES
Environment=WLR_DRM_DEVICES=/dev/dri/card1:/dev/dri/card0
